### ISSUE TITLE
current p2p speed

### ISSUE THREAD

**Issue by shell1986** [cdnbye/OMS#1]
Good afternoon, I am very glad that you are adding new opportunities for analytics. I think many will be interested in the current speed of all users in the statistics OMS.

It would also be nice to add a time zone setting when updating information.

**Comment by snowinszu** [comment]
Under development

**Comment by supersh86** [comment]
Вы можете это сделать разделив разницу отданных мегабайт на время обновление.

(new_totalbyte-old_totalbyte)/timeupdate_in_sec

**Comment by snowinszu** [comment]
all done :)
